language: rust
cache: cargo

os:
  - linux
  - osx

rust:
  - stable
  - beta
  - nightly

script:
  - cargo build --release
  - cargo test --locked
  - pwd
  - ls -la /home/travis/build/nhatdo-nfq/dssim
  - ls -la /home/travis/build/nhatdo-nfq/dssim/target
  - ls -la /home/travis/build/nhatdo-nfq/dssim/target/release/dssim
