language: rust
cache: cargo

os:
    - linux
    - osx

rust:
    - stable
    - beta
    - nightly

script:
    - cargo build --release
    - cargo test --locked
    - pwd
    - ls -la $TRAVIS_BUILD_DIR/target/release/dssim
    - cp ./target/release/dssim ./$TRAVIS_OS_NAME-dssim

deploy:
    provider: releases
    tag_name: $TRAVIS_BUILD_NUMBER
    target_commitish: $TRAVIS_COMMIT
    name: $TRAVIS_BUILD_NUMBER
    overwrite: true
    skip_cleanup: true
    api_key: $github_token
    file_glob: true
    file:
        - $TRAVIS_BUILD_DIR/nhatdo-nfq/dssim/linux-dssim
        - $TRAVIS_BUILD_DIR/nhatdo-nfq/dssim/osx-dssim
    on:
        all_branches: true
